### ISSUE TITLE
The LCMC value of MDS and PCA  are equal ？Why?

### ISSUE THREAD

**Issue by lily1720** [gdkrmr/coRanking#1]
![Rplot01](https://user-images.githubusercontent.com/18440596/61262387-a88a4b00-a7b7-11e9-945c-723ce0dbdf10.jpeg)
![Rplot2](https://user-images.githubusercontent.com/18440596/61262389-a922e180-a7b7-11e9-8392-532ef174c354.jpeg)

**Comment by gdkrmr** [comment]
If you used the classical Torgerson MDS with Euclidean distances, the results will be identical to PCA, see e.g. https://stats.stackexchange.com/questions/14002/whats-the-difference-between-principal-component-analysis-and-multidimensional
