### ISSUE TITLE
Inverse function for tsne and umap

### ISSUE THREAD

**Issue by nikitagupta0809** [gdkrmr/coRanking#2]
Hi,
I am trying to find the reconstruction error for umap and tsne. I get this error.

ir <- loadDataSet("3D S Curve")
    ir.umap <- embed(ir, "UMAP", ndim = ndims(ir))
    ir.tsne <- embed(ir, "tSNE", ndim = ndims(ir))
    rmse <- data.frame(
      rmse_umap = reconstruction_error(ir.umap),
      rmse_tsne = reconstruction_error(ir.tsne)
    )
    matplot(rmse, type = "l")
    plot(ir)
    plot(ir.umap)
    plot(ir.tsne)

This gives me an error: 
Error in .local(object, ...): object does not have an inverse function
Traceback:

1. data.frame(rmse_umap = reconstruction_error(ir.umap), rmse_tsne = reconstruction_error(ir.tsne))
2. reconstruction_error(ir.umap)
3. reconstruction_error(ir.umap)
4. .local(object, ...)
5. getData(inverse(object, getData(getDimRedData(object))[, seq_len(n[i]), 
 .     drop = FALSE]))
6. inverse(object, getData(getDimRedData(object))[, seq_len(n[i]), 
 .     drop = FALSE])
7. inverse(object, getData(getDimRedData(object))[, seq_len(n[i]), 
 .     drop = FALSE])
8. .local(object, ...)
9. stop("object does not have an inverse function")

Please let me know where am I going wrong/ how to fix this issue. Thanks!

**Comment by gdkrmr** [comment]
That is a `dimRed` issue. There is no inverse for UMAP and tSNE.
